[package]
authors = ["Josh Chase <josh@prevoty.com>"]
description = "Rust bindings to the JNI"
documentation = "https://docs.rs/jni"
readme = "README.md"
keywords = [
    "ffi",
    "jni",
    "java",
]
categories = ["api-bindings"]
license = "MIT/Apache-2.0"
name = "jni"
repository = "https://github.com/jni-rs/jni-rs"
# Â¡When bumping version please also update it in examples and documentation!
version = "0.21.0-alpha.0"
edition = "2018"

[dependencies]
cesu8 = "1.1.0"
cfg-if = { version = "1", optional = true }
combine = "4.1.0"
java-locator = { version = "0.1", optional = true }
jni-sys = "0.3.0"
libloading = { version = "0.6", optional = true }
log = "0.4.4"
once_cell = { version = "1", optional = true }
thiserror = "1.0.20"

[build-dependencies]
walkdir = "2"

[dev-dependencies]
lazy_static = "1"


[features]
invocation = ["cfg-if"]
invocation-dyn = ["invocation", "java-locator", "libloading", "once_cell"]
default = []

[package.metadata.docs.rs]
features = ["invocation-dyn"]
