[package]
authors = ["Josh Chase <josh@prevoty.com>"]
description = "Rust bindings to the JNI"
documentation = "https://docs.rs/jni"
homepage = "https://docs.rs/jni"
readme = "README.md"
keywords = [
    "ffi",
    "jni",
    "java",
]
categories = ["api-bindings"]
license = "MIT/Apache-2.0"
name = "jni"
repository = "https://github.com/jni-rs/jni-rs"
# Â¡When bumping version please also update it in examples and documentation!
version = "0.12.2"

[dependencies]
cesu8 = "1.1.0"
combine = "3.4.1"
jni-sys = "0.3.0"
log = "0.4.4"
lazy_static = "1"

[build-dependencies]
walkdir = "2"

[dependencies.error-chain]
default-features = false
version = "0.12.0"


[features]
invocation = []
backtrace = ["error-chain/backtrace"]
default = ["backtrace"]
