[package]
name = "jni"
version = "0.4.4"
authors = ["Josh Chase <josh@prevoty.com>"]
description = "Rust bindings to the JNI"
license = "MIT/Apache-2.0"
keywords = ["ffi", "jni", "java"]
repository = "https://github.com/prevoty/jni-rs"
documentation = "https://docs.rs/jni"
homepage = "https://docs.rs/jni"

[dependencies]
log = "0.3"
combine = "2"
cesu8 = "1"
jni-sys = "^0.2.5"
error-chain = { version = "0.10", default-features = false }

[features]
default = ["backtrace"]
backtrace = ["error-chain/backtrace"]
